# Generated by Django 5.2.7 on 2025-11-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('teacher', '0002_alter_teacher_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
