# Generated by Django 5.2.7 on 2025-11-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_academicyear_systemsetting_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='mate',
        ),
        migrations.AddField(
            model_name='log',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
